apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cicd-tools
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cicd-tools
    app.kubernetes.io/part-of: cicd-tools
  name: cicd-tools
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: cicd-tools
status:
  loadBalancer: {}
